// apps/carrito-svelte/src/App.svelte
<!-- <svelte:options immutable={true} /> -->
<script>
  import CartItem from "./components/CartItem.svelte";
  import Filters from "./components/Filters.svelte";
  import Product from "./components/Product.svelte";
  import filters from "./stores/filters";
  import { products } from "./stores/products";
  import { customCart } from "./stores/cart";
  import { filterProducts } from "./utils/productsUtils";

  let carroDisplay = "block";
  $: filteredProducts = filterProducts({
    products: $products,
    filters: $filters,
  });
</script>

<div class="wrapper">
  <div>
    <main class="shopping">
      <header>
        <h1>Svelte Store</h1>
        <button
          on:click={() => {
            carroDisplay = carroDisplay === "none" ? "block" : "none";
          }}>Carro</button
        >
      </header>
      <Filters />
      <section class="product-list">
        {#each filteredProducts as product (product.id)}
          <Product {...product} />
        {/each}
      </section>
    </main>
  </div>
  <aside class="carro" style={`display:${carroDisplay}`}>
    <h1>Carro</h1>
    {#each $customCart as cp (cp.id)}
      <CartItem {...cp} />
    {/each}
  </aside>
  <footer>
    Github repo <a
      href="https://github.com/SFToro/exercises/tree/main/apps/carrito-svelte"
      >Here</a
    >
  </footer>
</div>

<style>
  footer {
    position: sticky;
    background-color: rgba(255, 255, 255, 0.7);
    width: fit-content;
    padding: 1rem;
    border-radius: 0.5rem;
    bottom: 1rem;
    left: 1rem;
  }
</style>

// apps/carrito-react/src/App.jsx
import { useState, useContext } from "react";
import "./App.css";
import Product from "./components/Product";
import Filters from "./components/Filters";
import CartItem from "./components/CartItem";

import { products } from "./mocks/products.json";
import { useFilters } from "./hooks/useFilters";
import { CartContext } from "./context/cart";

function App() {
  const { filteredProducts } = useFilters(products);
  const [carroDisplay, setCarroDisplay] = useState(true);

  const { cartList, resetCart } = useContext(CartContext);

  return (
    <>
      <div className="flex">
        <main className="shopping">
          <header>
            <h1>React Mock store</h1>
            <button
              onClick={() => {
                setCarroDisplay(!carroDisplay);
              }}
            >
              Carro
            </button>
          </header>
          <Filters />
          <section className="product-list">
            {filteredProducts.map((product) => {
              return <Product key={product.id} product={product}></Product>;
            })}
          </section>
        </main>
        <aside
          className="carro"
          style={{ display: carroDisplay ? "block" : "none" }}
        >
          <h3>Carro</h3>
          <button
            style={{ color: "#000", backgroundColor: "#ccc" }}
            onClick={resetCart}
          >
            reset
          </button>
          {cartList.map((product) => (
            <CartItem product={product} key={product.id} />
          ))}
        </aside>
      </div>

      <footer className="repo">
        Github repo{" "}
        <a href="https://github.com/SFToro/exercises/tree/main/apps/carrito-react">
          Here
        </a>
      </footer>
    </>
  );
}

export default App;
