// apps/pelis-svelte/src/App.svelte
<script>
  import { onDestroy } from 'svelte'
  import Movie from './components/Movie.svelte'
  import { getMovies } from './lib/getMovies'
  import { isSearchValid } from './lib/validation'

  let query, lastSearch
  let moviesPromise
  let timer, debouncedInput

  function handleSubmit(e) {
    e.preventDefault()
    const { query } = Object.fromEntries(new window.FormData(e.target))
    if (!isSearchValid({ query, lastSearch })) return

    moviesPromise = getMovies({
      query,
      lastSearch,
    })
  }

  const debounce = (query) => {
    clearTimeout(timer)
    timer = setTimeout(() => {
      debouncedInput = query
    }, 750)
  }

  $: if (isSearchValid({ query: debouncedInput, lastSearch })) {
    console.log(debouncedInput)
    moviesPromise = getMovies({
      query: debouncedInput,
      lastSearch,
    })
  }

  onDestroy(() => {
    clearTimeout(timer)
  })
</script>

<main>
  <form action="submit" on:submit={handleSubmit}>
    <label>
      Nombre de la peli:
      <input
        name="query"
        type="text"
        on:keyup={(e) => {
          debounce(e.target.value)
        }}
      />
    </label>
    <button type="submit">Buscar</button>

    {#if debouncedInput}
      <p>{debouncedInput}</p>
    {/if}
  </form>
  {#if moviesPromise}
    {#await moviesPromise}
      <h2>
        Loading movies...If it takes too long the API key might have got
        pwned...
      </h2>
    {:then movies}
      <section class="movies">
        {#each movies as movie (movie.id)}
          <Movie {movie} />
        {/each}
      </section>
    {:catch e}
      <h2>There is a problem: {e}</h2>
    {/await}
  {/if}
</main>
<footer>
  Github repo <a
    href="https://github.com/SFToro/exercises/tree/main/apps/pelis-svelte"
    >Here</a
  >
</footer>

<style>
  footer {
    position: fixed;
    background-color: rgba(255, 255, 255, 0.7);
    width: fit-content;
    padding: 1rem;
    border-radius: 0.5rem;
    bottom: 1rem;
    left: 1rem;
  }
</style>

// apps/pelis-react/src/App.jsx
import "./App.css";
import Movie from "./components/Movie";
import { useMovies } from "./hooks/useMovies";
import { useDebouncer } from "./hooks/useDebouncer";

function App() {
  // Hook
  const {
    fetchedMovies,
    sortedMovies,
    isLoading,
    error,
    isSorted,
    getMappedMovies,
    sortMovies,
  } = useMovies();
  const { debounce, debouncedInput } = useDebouncer();

  let movies;
  if (isSorted === true) {
    movies = sortedMovies;
  } else {
    movies = fetchedMovies;
  }

  function handleSubmit(evt) {
    evt.preventDefault();
    const { query } = Object.fromEntries(new FormData(evt.target));
    getMappedMovies({ query });
  }

  return (
    <>
      <main>
        <form
          action="submit"
          onSubmit={(evt) => {
            handleSubmit(evt);
          }}
        >
          <label>
            Nombre de la peli:
            <input
              name="query"
              type="text"
              onKeyUp={(evt) => {
                const debouncePromise = async ({ query }) => {
                  const debouncedQuery = await debounce({ query });
                  getMappedMovies({ query: debouncedQuery });
                };
                debouncePromise({ query: evt.target.value });
                // debounce({ query: evt.target.value, cb: getMappedMovies });
              }}
            />
          </label>
          <label htmlFor="sort">
            Sort by title:
            <input
              type="checkbox"
              name="sort"
              id="sort"
              onChange={() => {
                sortMovies();
              }}
            />
          </label>
          <button type="submit">Buscar</button>

          <p>{debouncedInput}</p>
        </form>
        <section style={{ display: "flex", justifyContent: "center" }}>
          {error && <h2>There is a problem: {error}</h2>}
          {isLoading && (
            <h2>
              Loading movies...If it takes too long the API key might have got
              pwned...
            </h2>
          )}
        </section>
        {!error && !isLoading && (
          <section className="movies">
            {movies.map((movie, idx) => (
              <Movie key={idx} {...movie} />
            ))}
          </section>
        )}
      </main>
      <footer className="repo">
        Github repo{" "}
        <a href="https://github.com/SFToro/exercises/tree/main/apps/pelis-react">
          Here
        </a>
      </footer>
    </>
  );
}

export default App;
