// apps/carrito-react/src/components/Product.jsx
import { CartContext } from "../context/cart";
import { useContext } from "react";

function Product({ product }) {
  const { title, description, thumbnail, id } = product;
  const { addToCart, cartList, isInCart } = useContext(CartContext);

  // function isInCart(idx) {
  //   cartList.some((item) => {
  //     item.id === idx;
  //   });
  // }

  return (
    <article className="product">
      <h3>{title}</h3>
      <p>{description}</p>

      {!isInCart(id) && (
        <button
          onClick={() => {
            addToCart(product);
          }}
          style={{ color: "#000", backgroundColor: "#ccc" }}
        >
          Al carro
        </button>
      )}
      <img src={thumbnail} alt={description} />
    </article>
  );
}

export default Product;

// apps/carrito-svelte/src/components/Product.svelte
<!-- <svelte:options immutable={true} /> -->
<script>
  import { customCart } from "../stores/cart";
  import { afterUpdate } from "svelte";
  import flash from "../utils/flash";

  let cantidad;
  export let title, description, id, thumbnail, stock, isInCart;

  afterUpdate(() => {
    if (isInCart) flash(cantidad);
  });
</script>

<article class="product">
  <h3>{title}</h3>
  <p>{description}</p>
  <p bind:this={cantidad}>stonk: {stock}</p>
  {#if !isInCart}
    <button
      on:click={() => {
        customCart.addToCart(id);
      }}
      style="height: 40px;width: 150px;margin-inline:auto">Al carro</button
    >
  {/if}
  <img src={thumbnail} alt={description} />
</article>
